export const SET_CURRENT_USER='SET_CURRENT_USER';
export const FETCH_TENANTS = 'FETCH_TENANTS';
export const FETCH_TENANT = 'FETCH_TENANT';
export const DELETE_TENANT = 'DELETE_TENANT';
export const EDIT_TENANT = 'EDIT_TENANT';
export const ADD_TENANT = 'ADD_TENANT';
